# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NfcFeubbQqf5wvn_BnCss71oajI8tZGR
"""

while True:
  print('|' + '-'*70 + '|')
  print('|' + ' '*13 + "Program Menghitung Estimasi Waktu Perjalanan" + ' '*13 + '|')
  print('|' + '-'*70 + '|')
  print('|' + '1. Jalankan Program' + ' '*51 + '|')
  print('|' + '2. Keluar Program' + ' '*53 + '|')
  print('|' + '-'*70 + '|')
  a = input('Pilih Fitur ')
  print('\n')
  if a == '1':
    print('|' + '-'*70 + '|')
    print('|' + ' '*13 + "Program Menghitung Estimasi Waktu Perjalanan" + ' '*13 + '|')
    print('|' + '-'*70 + '|')
    jarak = input('Masukkan jarak yang akan anda tempuh (Km) ')
    kecepatan = input('Masukkan kecepatan rata - rata dari kendaraan anda (Km/Jam) ')
    waktu = int(jarak) / int(kecepatan)
    print('\n')
    print('|' + '-'*70 + '|')
    print('|' + ' '*13 + "Program Menghitung Estimasi Waktu Perjalanan" + ' '*13 + '|')
    print('|' + '-'*70 + '|')
    print('Waktu perjalanan yang akan ditempuh adalah', int(waktu), 'jam')
    print('\n')
  else:
    print('|' + '-'*70 + '|')
    print('|' + ' '*13 + "Program Menghitung Estimasi Waktu Perjalanan" + ' '*13 + '|')
    print('|' + '-'*70 + '|')
    print('|' + ' '*14 + "Terimakasih telah menggunakan program ini " + ' '*14 + '|') 
    print('|' + '-'*70 + '|')
    break